# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T10:18:06+00:00



import argparse
import json
import os
from typing import *
from typing import Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity
from fastapi import UploadFile
from starlette.requests import Request

from models import (
    AddStickerToSetPostResponse,
    AnswerCallbackQueryPostRequest,
    AnswerCallbackQueryPostResponse,
    AnswerInlineQueryPostRequest,
    AnswerInlineQueryPostResponse,
    AnswerPreCheckoutQueryPostRequest,
    AnswerPreCheckoutQueryPostResponse,
    AnswerShippingQueryPostRequest,
    AnswerShippingQueryPostResponse,
    ClosePostResponse,
    CopyMessagePostRequest,
    CopyMessagePostResponse,
    CreateNewStickerSetPostResponse,
    DeleteChatPhotoPostRequest,
    DeleteChatPhotoPostResponse,
    DeleteChatStickerSetPostRequest,
    DeleteChatStickerSetPostResponse,
    DeleteMessagePostRequest,
    DeleteMessagePostResponse,
    DeleteStickerFromSetPostRequest,
    DeleteStickerFromSetPostResponse,
    DeleteWebhookPostRequest,
    DeleteWebhookPostResponse,
    EditMessageCaptionPostRequest,
    EditMessageCaptionPostResponse,
    EditMessageLiveLocationPostRequest,
    EditMessageLiveLocationPostResponse,
    EditMessageMediaPostResponse,
    EditMessageReplyMarkupPostRequest,
    EditMessageReplyMarkupPostResponse,
    EditMessageTextPostRequest,
    EditMessageTextPostResponse,
    Error,
    ExportChatInviteLinkPostRequest,
    ExportChatInviteLinkPostResponse,
    ForwardMessagePostRequest,
    ForwardMessagePostResponse,
    GetChatAdministratorsPostRequest,
    GetChatAdministratorsPostResponse,
    GetChatMemberPostRequest,
    GetChatMemberPostResponse,
    GetChatMembersCountPostRequest,
    GetChatMembersCountPostResponse,
    GetChatPostRequest,
    GetChatPostResponse,
    GetFilePostRequest,
    GetFilePostResponse,
    GetGameHighScoresPostRequest,
    GetGameHighScoresPostResponse,
    GetMePostResponse,
    GetMyCommandsPostResponse,
    GetStickerSetPostRequest,
    GetStickerSetPostResponse,
    GetUpdatesPostRequest,
    GetUpdatesPostResponse,
    GetUserProfilePhotosPostRequest,
    GetUserProfilePhotosPostResponse,
    GetWebhookInfoPostResponse,
    KickChatMemberPostRequest,
    KickChatMemberPostResponse,
    LeaveChatPostRequest,
    LeaveChatPostResponse,
    LogOutPostResponse,
    PinChatMessagePostRequest,
    PinChatMessagePostResponse,
    PromoteChatMemberPostRequest,
    PromoteChatMemberPostResponse,
    RestrictChatMemberPostRequest,
    RestrictChatMemberPostResponse,
    SendAnimationPostResponse,
    SendAudioPostResponse,
    SendChatActionPostRequest,
    SendChatActionPostResponse,
    SendContactPostRequest,
    SendContactPostResponse,
    SendDicePostRequest,
    SendDicePostResponse,
    SendDocumentPostResponse,
    SendGamePostRequest,
    SendGamePostResponse,
    SendInvoicePostRequest,
    SendInvoicePostResponse,
    SendLocationPostRequest,
    SendLocationPostResponse,
    SendMediaGroupPostResponse,
    SendMessagePostRequest,
    SendMessagePostResponse,
    SendPhotoPostResponse,
    SendPollPostRequest,
    SendPollPostResponse,
    SendStickerPostResponse,
    SendVenuePostRequest,
    SendVenuePostResponse,
    SendVideoNotePostResponse,
    SendVideoPostResponse,
    SendVoicePostResponse,
    SetChatAdministratorCustomTitlePostRequest,
    SetChatAdministratorCustomTitlePostResponse,
    SetChatDescriptionPostRequest,
    SetChatDescriptionPostResponse,
    SetChatPermissionsPostRequest,
    SetChatPermissionsPostResponse,
    SetChatPhotoPostResponse,
    SetChatStickerSetPostRequest,
    SetChatStickerSetPostResponse,
    SetChatTitlePostRequest,
    SetChatTitlePostResponse,
    SetGameScorePostRequest,
    SetGameScorePostResponse,
    SetMyCommandsPostRequest,
    SetMyCommandsPostResponse,
    SetPassportDataErrorsPostRequest,
    SetPassportDataErrorsPostResponse,
    SetStickerPositionInSetPostRequest,
    SetStickerPositionInSetPostResponse,
    SetStickerSetThumbPostResponse,
    SetWebhookPostResponse,
    StopMessageLiveLocationPostRequest,
    StopMessageLiveLocationPostResponse,
    StopPollPostRequest,
    StopPollPostResponse,
    UnbanChatMemberPostRequest,
    UnbanChatMemberPostResponse,
    UnpinAllChatMessagesPostRequest,
    UnpinAllChatMessagesPostResponse,
    UnpinChatMessagePostRequest,
    UnpinChatMessagePostResponse,
    UploadStickerFilePostResponse,
)

app = MCPProxy(
    description='Auto-generated OpenAPI schema',
    title='Telegram Bot API',
    version='5.0.0',
    servers=[
        {
            'url': 'https://api.telegram.org/bot{token}',
            'variables': {
                'token': {
                    'default': '123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11',
                    'description': 'Each bot is given a unique authentication token when it is created.',
                }
            },
        }
    ],
)


@app.post(
    '/addStickerToSet',
    description=""" Use this method to add a new sticker to a set created by the bot. You **must** use exactly one of the fields *png\_sticker* or *tgs\_sticker*. Animated stickers can be added to animated sticker sets and only to them. Animated sticker sets can have up to 50 stickers. Static sticker sets can have up to 120 stickers. Returns *True* on success. """,
    tags=['file_handling'],
)
def post_add_sticker_to_set(file: UploadFile):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/answerCallbackQuery',
    description=""" Use this method to send answers to callback queries sent from [inline keyboards](/bots#inline-keyboards-and-on-the-fly-updating). The answer will be displayed to the user as a notification at the top of the chat screen or as an alert. On success, *True* is returned.

Alternatively, the user can be redirected to the specified Game URL. For this option to work, you must first create a game for your bot via [@Botfather](https://t.me/botfather) and accept the terms. Otherwise, you may use links like `t.me/your_bot?start=XXXX` that open your bot with a parameter. """,
    tags=['callback_and_query_handling'],
)
def post_answer_callback_query(body: AnswerCallbackQueryPostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/answerInlineQuery',
    description=""" Use this method to send answers to an inline query. On success, *True* is returned.  
No more than **50** results per query are allowed. """,
    tags=['callback_and_query_handling'],
)
def post_answer_inline_query(body: AnswerInlineQueryPostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/answerPreCheckoutQuery',
    description=""" Once the user has confirmed their payment and shipping details, the Bot API sends the final confirmation in the form of an [Update](https://core.telegram.org/bots/api/#update) with the field *pre\_checkout\_query*. Use this method to respond to such pre-checkout queries. On success, True is returned. **Note:** The Bot API must receive an answer within 10 seconds after the pre-checkout query was sent. """,
    tags=['callback_and_query_handling'],
)
def post_answer_pre_checkout_query(body: AnswerPreCheckoutQueryPostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/answerShippingQuery',
    description=""" If you sent an invoice requesting a shipping address and the parameter *is\_flexible* was specified, the Bot API will send an [Update](https://core.telegram.org/bots/api/#update) with a *shipping\_query* field to the bot. Use this method to reply to shipping queries. On success, True is returned. """,
    tags=['callback_and_query_handling'],
)
def post_answer_shipping_query(body: AnswerShippingQueryPostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/close',
    description=""" Use this method to close the bot instance before moving it from one local server to another. You need to delete the webhook before calling this method to ensure that the bot isn't launched again after server restart. The method will return error 429 in the first 10 minutes after the bot is launched. Returns *True* on success. Requires no parameters. """,
    tags=['chat_operations'],
)
def post_close():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/copyMessage',
    description=""" Use this method to copy messages of any kind. The method is analogous to the method [forwardMessages](https://core.telegram.org/bots/api/#forwardmessages), but the copied message doesn't have a link to the original message. Returns the [MessageId](https://core.telegram.org/bots/api/#messageid) of the sent message on success. """,
    tags=['message_management'],
)
def post_copy_message(body: CopyMessagePostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/createNewStickerSet',
    description=""" Use this method to create a new sticker set owned by a user. The bot will be able to edit the sticker set thus created. You **must** use exactly one of the fields *png\_sticker* or *tgs\_sticker*. Returns *True* on success. """,
    tags=['file_handling'],
)
def post_create_new_sticker_set(file: UploadFile):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/deleteChatPhoto',
    description=""" Use this method to delete a chat photo. Photos can't be changed for private chats. The bot must be an administrator in the chat for this to work and must have the appropriate admin rights. Returns *True* on success. """,
    tags=['chat_operations'],
)
def post_delete_chat_photo(body: DeleteChatPhotoPostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/deleteChatStickerSet',
    description=""" Use this method to delete a group sticker set from a supergroup. The bot must be an administrator in the chat for this to work and must have the appropriate admin rights. Use the field *can\_set\_sticker\_set* optionally returned in [getChat](https://core.telegram.org/bots/api/#getchat) requests to check if the bot can use this method. Returns *True* on success. """,
    tags=['sticker_set_management', 'sticker_management_for_chats'],
)
def post_delete_chat_sticker_set(body: DeleteChatStickerSetPostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/deleteMessage',
    description=""" Use this method to delete a message, including service messages, with the following limitations:  
\- A message can only be deleted if it was sent less than 48 hours ago.  
\- A dice message in a private chat can only be deleted if it was sent more than 24 hours ago.  
\- Bots can delete outgoing messages in private chats, groups, and supergroups.  
\- Bots can delete incoming messages in private chats.  
\- Bots granted *can\_post\_messages* permissions can delete outgoing messages in channels.  
\- If the bot is an administrator of a group, it can delete any message there.  
\- If the bot has *can\_delete\_messages* permission in a supergroup or a channel, it can delete any message there.  
Returns *True* on success. """,
    tags=['message_management'],
)
def post_delete_message(body: DeleteMessagePostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/deleteStickerFromSet',
    description=""" Use this method to delete a sticker from a set created by the bot. Returns *True* on success. """,
    tags=['sticker_set_management', 'sticker_management_for_chats'],
)
def post_delete_sticker_from_set(body: DeleteStickerFromSetPostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/deleteWebhook',
    description=""" Use this method to remove webhook integration if you decide to switch back to [getUpdates](https://core.telegram.org/bots/api/#getupdates). Returns *True* on success. """,
    tags=['webhook_configuration'],
)
def post_delete_webhook(body: DeleteWebhookPostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/editMessageCaption',
    description=""" Use this method to edit captions of messages. On success, if the edited message is not an inline message, the edited [Message](https://core.telegram.org/bots/api/#message) is returned, otherwise *True* is returned. """,
    tags=['message_management'],
)
def post_edit_message_caption(body: EditMessageCaptionPostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/editMessageLiveLocation',
    description=""" Use this method to edit live location messages. A location can be edited until its *live\_period* expires or editing is explicitly disabled by a call to [stopMessageLiveLocation](https://core.telegram.org/bots/api/#stopmessagelivelocation). On success, if the edited message is not an inline message, the edited [Message](https://core.telegram.org/bots/api/#message) is returned, otherwise *True* is returned. """,
    tags=['message_management', 'live_location_sharing_management'],
)
def post_edit_message_live_location(body: EditMessageLiveLocationPostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/editMessageMedia',
    description=""" Use this method to edit animation, audio, document, photo, or video messages. If a message is part of a message album, then it can be edited only to an audio for audio albums, only to a document for document albums and to a photo or a video otherwise. When an inline message is edited, a new file can't be uploaded. Use a previously uploaded file via its file\_id or specify a URL. On success, if the edited message was sent by the bot, the edited [Message](https://core.telegram.org/bots/api/#message) is returned, otherwise *True* is returned. """,
    tags=['file_handling'],
)
def post_edit_message_media(file: UploadFile):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/editMessageReplyMarkup',
    description=""" Use this method to edit only the reply markup of messages. On success, if the edited message is not an inline message, the edited [Message](https://core.telegram.org/bots/api/#message) is returned, otherwise *True* is returned. """,
    tags=['message_management'],
)
def post_edit_message_reply_markup(body: EditMessageReplyMarkupPostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/editMessageText',
    description=""" Use this method to edit text and [game](https://core.telegram.org/bots/api/#games) messages. On success, if the edited message is not an inline message, the edited [Message](https://core.telegram.org/bots/api/#message) is returned, otherwise *True* is returned. """,
    tags=['message_management'],
)
def post_edit_message_text(body: EditMessageTextPostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/exportChatInviteLink',
    description=""" Use this method to generate a new invite link for a chat; any previously generated link is revoked. The bot must be an administrator in the chat for this to work and must have the appropriate admin rights. Returns the new invite link as *String* on success. """,
    tags=['chat_operations'],
)
def post_export_chat_invite_link(body: ExportChatInviteLinkPostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/forwardMessage',
    description=""" Use this method to forward messages of any kind. On success, the sent [Message](https://core.telegram.org/bots/api/#message) is returned. """,
    tags=['message_management'],
)
def post_forward_message(body: ForwardMessagePostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/getChat',
    description=""" Use this method to get up to date information about the chat (current name of the user for one-on-one conversations, current username of a user, group or channel, etc.). Returns a [Chat](https://core.telegram.org/bots/api/#chat) object on success. """,
    tags=['chat_operations'],
)
def post_get_chat(body: GetChatPostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/getChatAdministrators',
    description=""" Use this method to get a list of administrators in a chat. On success, returns an Array of [ChatMember](https://core.telegram.org/bots/api/#chatmember) objects that contains information about all chat administrators except other bots. If the chat is a group or a supergroup and no administrators were appointed, only the creator will be returned. """,
    tags=['chat_member_admin_management', 'user_and_member_management'],
)
def post_get_chat_administrators(body: GetChatAdministratorsPostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/getChatMember',
    description=""" Use this method to get information about a member of a chat. Returns a [ChatMember](https://core.telegram.org/bots/api/#chatmember) object on success. """,
    tags=['user_and_member_management', 'chat_operations'],
)
def post_get_chat_member(body: GetChatMemberPostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/getChatMembersCount',
    description=""" Use this method to get the number of members in a chat. Returns *Int* on success. """,
    tags=['user_and_member_management', 'chat_operations'],
)
def post_get_chat_members_count(body: GetChatMembersCountPostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/getFile',
    description=""" Use this method to get basic info about a file and prepare it for downloading. For the moment, bots can download files of up to 20MB in size. On success, a [File](https://core.telegram.org/bots/api/#file) object is returned. The file can then be downloaded via the link `https://api.telegram.org/file/bot<token>/<file_path>`, where `<file_path>` is taken from the response. It is guaranteed that the link will be valid for at least 1 hour. When the link expires, a new one can be requested by calling [getFile](https://core.telegram.org/bots/api/#getfile) again. """,
    tags=['file_handling'],
)
def post_get_file(body: GetFilePostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/getGameHighScores',
    description=""" Use this method to get data for high score tables. Will return the score of the specified user and several of their neighbors in a game. On success, returns an *Array* of [GameHighScore](https://core.telegram.org/bots/api/#gamehighscore) objects.

This method will currently return scores for the target user, plus two of their closest neighbors on each side. Will also return the top three users if the user and his neighbors are not among them. Please note that this behavior is subject to change. """,
    tags=['game_scoring_management'],
)
def post_get_game_high_scores(body: GetGameHighScoresPostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/getMe',
    description=""" A simple method for testing your bot's auth token. Requires no parameters. Returns basic information about the bot in form of a [User](https://core.telegram.org/bots/api/#user) object. """,
    tags=[
        'sticker_set_management',
        'chat_operations',
        'message_management',
        'callback_and_query_handling',
        'user_and_member_management',
        'file_handling',
        'user_profile_handling',
        'chat_member_admin_management',
        'chat_media_sending',
        'chat_settings_configuration',
        'sticker_management_for_chats',
        'chat_title_settings',
        'game_scoring_management',
        'bot_command_handling',
        'passport_data_error_handling',
        'live_location_sharing_management',
        'poll_handling',
        'webhook_configuration',
        'pinned_message_management',
    ],
)
def post_get_me():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/getMyCommands',
    description=""" Use this method to get the current list of the bot's commands. Requires no parameters. Returns Array of [BotCommand](https://core.telegram.org/bots/api/#botcommand) on success. """,
    tags=['sticker_set_management'],
)
def post_get_my_commands():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/getStickerSet',
    description=""" Use this method to get a sticker set. On success, a [StickerSet](https://core.telegram.org/bots/api/#stickerset) object is returned. """,
    tags=['sticker_set_management', 'sticker_management_for_chats'],
)
def post_get_sticker_set(body: GetStickerSetPostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/getUpdates',
    description=""" Use this method to receive incoming updates using long polling ([wiki](https://en.wikipedia.org/wiki/Push_technology#Long_polling)). An Array of [Update](https://core.telegram.org/bots/api/#update) objects is returned. """,
    tags=['callback_and_query_handling'],
)
def post_get_updates(body: GetUpdatesPostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/getUserProfilePhotos',
    description=""" Use this method to get a list of profile pictures for a user. Returns a [UserProfilePhotos](https://core.telegram.org/bots/api/#userprofilephotos) object. """,
    tags=['user_profile_handling'],
)
def post_get_user_profile_photos(body: GetUserProfilePhotosPostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/getWebhookInfo',
    description=""" Use this method to get current webhook status. Requires no parameters. On success, returns a [WebhookInfo](https://core.telegram.org/bots/api/#webhookinfo) object. If the bot is using [getUpdates](https://core.telegram.org/bots/api/#getupdates), will return an object with the *url* field empty. """,
    tags=['chat_operations'],
)
def post_get_webhook_info():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/kickChatMember',
    description=""" Use this method to kick a user from a group, a supergroup or a channel. In the case of supergroups and channels, the user will not be able to return to the group on their own using invite links, etc., unless [unbanned](https://core.telegram.org/bots/api/#unbanchatmember) first. The bot must be an administrator in the chat for this to work and must have the appropriate admin rights. Returns *True* on success. """,
    tags=['user_and_member_management', 'chat_member_admin_management'],
)
def post_kick_chat_member(body: KickChatMemberPostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/leaveChat',
    description=""" Use this method for your bot to leave a group, supergroup or channel. Returns *True* on success. """,
    tags=['chat_operations', 'user_and_member_management'],
)
def post_leave_chat(body: LeaveChatPostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/logOut',
    description=""" Use this method to log out from the cloud Bot API server before launching the bot locally. You **must** log out the bot before running it locally, otherwise there is no guarantee that the bot will receive updates. After a successful call, you can immediately log in on a local server, but will not be able to log in back to the cloud Bot API server for 10 minutes. Returns *True* on success. Requires no parameters. """,
    tags=[
        'sticker_set_management',
        'chat_operations',
        'message_management',
        'callback_and_query_handling',
        'user_and_member_management',
        'file_handling',
        'user_profile_handling',
        'chat_member_admin_management',
        'chat_media_sending',
        'chat_settings_configuration',
        'sticker_management_for_chats',
        'chat_title_settings',
        'game_scoring_management',
        'bot_command_handling',
        'passport_data_error_handling',
        'live_location_sharing_management',
        'poll_handling',
        'webhook_configuration',
        'pinned_message_management',
    ],
)
def post_log_out():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/pinChatMessage',
    description=""" Use this method to add a message to the list of pinned messages in a chat. If the chat is not a private chat, the bot must be an administrator in the chat for this to work and must have the 'can\_pin\_messages' admin right in a supergroup or 'can\_edit\_messages' admin right in a channel. Returns *True* on success. """,
    tags=['pinned_message_management'],
)
def post_pin_chat_message(body: PinChatMessagePostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/promoteChatMember',
    description=""" Use this method to promote or demote a user in a supergroup or a channel. The bot must be an administrator in the chat for this to work and must have the appropriate admin rights. Pass *False* for all boolean parameters to demote a user. Returns *True* on success. """,
    tags=['user_and_member_management', 'chat_member_admin_management'],
)
def post_promote_chat_member(body: PromoteChatMemberPostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/restrictChatMember',
    description=""" Use this method to restrict a user in a supergroup. The bot must be an administrator in the supergroup for this to work and must have the appropriate admin rights. Pass *True* for all permissions to lift restrictions from a user. Returns *True* on success. """,
    tags=['user_and_member_management', 'chat_member_admin_management'],
)
def post_restrict_chat_member(body: RestrictChatMemberPostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/sendAnimation',
    description=""" Use this method to send animation files (GIF or H.264/MPEG-4 AVC video without sound). On success, the sent [Message](https://core.telegram.org/bots/api/#message) is returned. Bots can currently send animation files of up to 50 MB in size, this limit may be changed in the future. """,
    tags=['file_handling'],
)
def post_send_animation(file: UploadFile):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/sendAudio',
    description=""" Use this method to send audio files, if you want Telegram clients to display them in the music player. Your audio must be in the .MP3 or .M4A format. On success, the sent [Message](https://core.telegram.org/bots/api/#message) is returned. Bots can currently send audio files of up to 50 MB in size, this limit may be changed in the future.

For sending voice messages, use the [sendVoice](https://core.telegram.org/bots/api/#sendvoice) method instead. """,
    tags=['file_handling'],
)
def post_send_audio(file: UploadFile):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/sendChatAction',
    description=""" Use this method when you need to tell the user that something is happening on the bot's side. The status is set for 5 seconds or less (when a message arrives from your bot, Telegram clients clear its typing status). Returns *True* on success.

Example: The [ImageBot](https://t.me/imagebot) needs some time to process a request and upload the image. Instead of sending a text message along the lines of “Retrieving image, please wait…”, the bot may use [sendChatAction](https://core.telegram.org/bots/api/#sendchataction) with *action* = *upload\_photo*. The user will see a “sending photo” status for the bot.

We only recommend using this method when a response from the bot will take a **noticeable** amount of time to arrive. """,
    tags=['chat_operations'],
)
def post_send_chat_action(body: SendChatActionPostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/sendContact',
    description=""" Use this method to send phone contacts. On success, the sent [Message](https://core.telegram.org/bots/api/#message) is returned. """,
    tags=['user_and_member_management'],
)
def post_send_contact(body: SendContactPostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/sendDice',
    description=""" Use this method to send an animated emoji that will display a random value. On success, the sent [Message](https://core.telegram.org/bots/api/#message) is returned. """,
    tags=['game_scoring_management'],
)
def post_send_dice(body: SendDicePostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/sendDocument',
    description=""" Use this method to send general files. On success, the sent [Message](https://core.telegram.org/bots/api/#message) is returned. Bots can currently send files of any type of up to 50 MB in size, this limit may be changed in the future. """,
    tags=['file_handling'],
)
def post_send_document(file: UploadFile):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/sendGame',
    description=""" Use this method to send a game. On success, the sent [Message](https://core.telegram.org/bots/api/#message) is returned. """,
    tags=['game_scoring_management'],
)
def post_send_game(body: SendGamePostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/sendInvoice',
    description=""" Use this method to send invoices. On success, the sent [Message](https://core.telegram.org/bots/api/#message) is returned. """,
    tags=['callback_and_query_handling'],
)
def post_send_invoice(body: SendInvoicePostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/sendLocation',
    description=""" Use this method to send point on the map. On success, the sent [Message](https://core.telegram.org/bots/api/#message) is returned. """,
    tags=['chat_media_sending', 'live_location_sharing_management'],
)
def post_send_location(body: SendLocationPostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/sendMediaGroup',
    description=""" Use this method to send a group of photos, videos, documents or audios as an album. Documents and audio files can be only grouped in an album with messages of the same type. On success, an array of [Messages](https://core.telegram.org/bots/api/#message) that were sent is returned. """,
    tags=['file_handling'],
)
def post_send_media_group(file: UploadFile):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/sendMessage',
    description=""" Use this method to send text messages. On success, the sent [Message](https://core.telegram.org/bots/api/#message) is returned. """,
    tags=['message_management', 'chat_media_sending'],
)
def post_send_message(body: SendMessagePostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/sendPhoto',
    description=""" Use this method to send photos. On success, the sent [Message](https://core.telegram.org/bots/api/#message) is returned. """,
    tags=['file_handling'],
)
def post_send_photo(file: UploadFile):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/sendPoll',
    description=""" Use this method to send a native poll. On success, the sent [Message](https://core.telegram.org/bots/api/#message) is returned. """,
    tags=['poll_handling'],
)
def post_send_poll(body: SendPollPostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/sendSticker',
    description=""" Use this method to send static .WEBP or [animated](https://telegram.org/blog/animated-stickers) .TGS stickers. On success, the sent [Message](https://core.telegram.org/bots/api/#message) is returned. """,
    tags=['file_handling'],
)
def post_send_sticker(file: UploadFile):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/sendVenue',
    description=""" Use this method to send information about a venue. On success, the sent [Message](https://core.telegram.org/bots/api/#message) is returned. """,
    tags=['chat_media_sending'],
)
def post_send_venue(body: SendVenuePostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/sendVideo',
    description=""" Use this method to send video files, Telegram clients support mp4 videos (other formats may be sent as [Document](https://core.telegram.org/bots/api/#document)). On success, the sent [Message](https://core.telegram.org/bots/api/#message) is returned. Bots can currently send video files of up to 50 MB in size, this limit may be changed in the future. """,
    tags=['file_handling'],
)
def post_send_video(file: UploadFile):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/sendVideoNote',
    description=""" As of [v.4.0](https://telegram.org/blog/video-messages-and-telescope), Telegram clients support rounded square mp4 videos of up to 1 minute long. Use this method to send video messages. On success, the sent [Message](https://core.telegram.org/bots/api/#message) is returned. """,
    tags=['file_handling'],
)
def post_send_video_note(file: UploadFile):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/sendVoice',
    description=""" Use this method to send audio files, if you want Telegram clients to display the file as a playable voice message. For this to work, your audio must be in an .OGG file encoded with OPUS (other formats may be sent as [Audio](https://core.telegram.org/bots/api/#audio) or [Document](https://core.telegram.org/bots/api/#document)). On success, the sent [Message](https://core.telegram.org/bots/api/#message) is returned. Bots can currently send voice messages of up to 50 MB in size, this limit may be changed in the future. """,
    tags=['file_handling'],
)
def post_send_voice(file: UploadFile):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/setChatAdministratorCustomTitle',
    description=""" Use this method to set a custom title for an administrator in a supergroup promoted by the bot. Returns *True* on success. """,
    tags=['chat_settings_configuration', 'chat_member_admin_management'],
)
def post_set_chat_administrator_custom_title(
    body: SetChatAdministratorCustomTitlePostRequest,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/setChatDescription',
    description=""" Use this method to change the description of a group, a supergroup or a channel. The bot must be an administrator in the chat for this to work and must have the appropriate admin rights. Returns *True* on success. """,
    tags=['chat_title_settings', 'chat_operations'],
)
def post_set_chat_description(body: SetChatDescriptionPostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/setChatPermissions',
    description=""" Use this method to set default chat permissions for all members. The bot must be an administrator in the group or a supergroup for this to work and must have the *can\_restrict\_members* admin rights. Returns *True* on success. """,
    tags=['chat_settings_configuration', 'user_and_member_management'],
)
def post_set_chat_permissions(body: SetChatPermissionsPostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/setChatPhoto',
    description=""" Use this method to set a new profile photo for the chat. Photos can't be changed for private chats. The bot must be an administrator in the chat for this to work and must have the appropriate admin rights. Returns *True* on success. """,
    tags=['file_handling'],
)
def post_set_chat_photo(file: UploadFile):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/setChatStickerSet',
    description=""" Use this method to set a new group sticker set for a supergroup. The bot must be an administrator in the chat for this to work and must have the appropriate admin rights. Use the field *can\_set\_sticker\_set* optionally returned in [getChat](https://core.telegram.org/bots/api/#getchat) requests to check if the bot can use this method. Returns *True* on success. """,
    tags=['sticker_set_management', 'sticker_management_for_chats'],
)
def post_set_chat_sticker_set(body: SetChatStickerSetPostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/setChatTitle',
    description=""" Use this method to change the title of a chat. Titles can't be changed for private chats. The bot must be an administrator in the chat for this to work and must have the appropriate admin rights. Returns *True* on success. """,
    tags=['chat_title_settings', 'chat_operations'],
)
def post_set_chat_title(body: SetChatTitlePostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/setGameScore',
    description=""" Use this method to set the score of the specified user in a game. On success, if the message was sent by the bot, returns the edited [Message](https://core.telegram.org/bots/api/#message), otherwise returns *True*. Returns an error, if the new score is not greater than the user's current score in the chat and *force* is *False*. """,
    tags=['game_scoring_management'],
)
def post_set_game_score(body: SetGameScorePostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/setMyCommands',
    description=""" Use this method to change the list of the bot's commands. Returns *True* on success. """,
    tags=['bot_command_handling'],
)
def post_set_my_commands(body: SetMyCommandsPostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/setPassportDataErrors',
    description=""" Informs a user that some of the Telegram Passport elements they provided contains errors. The user will not be able to re-submit their Passport to you until the errors are fixed (the contents of the field for which you returned the error must change). Returns *True* on success.

Use this if the data submitted by the user doesn't satisfy the standards your service requires for any reason. For example, if a birthday date seems invalid, a submitted document is blurry, a scan shows evidence of tampering, etc. Supply some details in the error message to make sure the user knows how to correct the issues. """,
    tags=['passport_data_error_handling'],
)
def post_set_passport_data_errors(body: SetPassportDataErrorsPostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/setStickerPositionInSet',
    description=""" Use this method to move a sticker in a set created by the bot to a specific position. Returns *True* on success. """,
    tags=['sticker_set_management', 'sticker_management_for_chats'],
)
def post_set_sticker_position_in_set(body: SetStickerPositionInSetPostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/setStickerSetThumb',
    description=""" Use this method to set the thumbnail of a sticker set. Animated thumbnails can be set for animated sticker sets only. Returns *True* on success. """,
    tags=['file_handling'],
)
def post_set_sticker_set_thumb(file: UploadFile):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/setWebhook',
    description=""" Use this method to specify a url and receive incoming updates via an outgoing webhook. Whenever there is an update for the bot, we will send an HTTPS POST request to the specified url, containing a JSON-serialized [Update](https://core.telegram.org/bots/api/#update). In case of an unsuccessful request, we will give up after a reasonable amount of attempts. Returns *True* on success.

If you'd like to make sure that the Webhook request comes from Telegram, we recommend using a secret path in the URL, e.g. `https://www.example.com/<token>`. Since nobody else knows your bot's token, you can be pretty sure it's us. """,
    tags=['file_handling'],
)
def post_set_webhook(file: UploadFile):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/stopMessageLiveLocation',
    description=""" Use this method to stop updating a live location message before *live\_period* expires. On success, if the message was sent by the bot, the sent [Message](https://core.telegram.org/bots/api/#message) is returned, otherwise *True* is returned. """,
    tags=['live_location_sharing_management'],
)
def post_stop_message_live_location(body: StopMessageLiveLocationPostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/stopPoll',
    description=""" Use this method to stop a poll which was sent by the bot. On success, the stopped [Poll](https://core.telegram.org/bots/api/#poll) with the final results is returned. """,
    tags=['poll_handling'],
)
def post_stop_poll(body: StopPollPostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/unbanChatMember',
    description=""" Use this method to unban a previously kicked user in a supergroup or channel. The user will **not** return to the group or channel automatically, but will be able to join via link, etc. The bot must be an administrator for this to work. By default, this method guarantees that after the call the user is not a member of the chat, but will be able to join it. So if the user is a member of the chat they will also be **removed** from the chat. If you don't want this, use the parameter *only\_if\_banned*. Returns *True* on success. """,
    tags=['user_and_member_management', 'chat_member_admin_management'],
)
def post_unban_chat_member(body: UnbanChatMemberPostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/unpinAllChatMessages',
    description=""" Use this method to clear the list of pinned messages in a chat. If the chat is not a private chat, the bot must be an administrator in the chat for this to work and must have the 'can\_pin\_messages' admin right in a supergroup or 'can\_edit\_messages' admin right in a channel. Returns *True* on success. """,
    tags=['pinned_message_management', 'chat_operations'],
)
def post_unpin_all_chat_messages(body: UnpinAllChatMessagesPostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/unpinChatMessage',
    description=""" Use this method to remove a message from the list of pinned messages in a chat. If the chat is not a private chat, the bot must be an administrator in the chat for this to work and must have the 'can\_pin\_messages' admin right in a supergroup or 'can\_edit\_messages' admin right in a channel. Returns *True* on success. """,
    tags=['pinned_message_management', 'chat_operations'],
)
def post_unpin_chat_message(body: UnpinChatMessagePostRequest):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/uploadStickerFile',
    description=""" Use this method to upload a .PNG file with a sticker for later use in *createNewStickerSet* and *addStickerToSet* methods (can be used multiple times). Returns the uploaded [File](https://core.telegram.org/bots/api/#file) on success. """,
    tags=['file_handling'],
)
def post_upload_sticker_file(file: UploadFile):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
